spring:
  application:
    name: library-events-consumer
  profiles:
    active: local
server:
  port: 8081
topics:
  retry: 'library-events.RETRY'
  dlt: 'library-events.DLT'

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: kafka-1839375a-library-inventory.k.aivencloud.com:18357
    topic:
      name: library-events
    security:
      protocol: SASL_SSL
    properties:
      sasl:
        mechanism: SCRAM-SHA-256
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:lib-event-db
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

